DK22Pac/plugin-sdk

src/sdk/game_sa/CMenuManager.h

Reopened the same merge request as the previous one got somewhat broken

CMenuManager fields

---

plugin_sa/events/EventList.cpp
plugin_sa/events/EventList.h

* initGameEvent
* reInitGameEvent

Readded game init events

---

plugin_sa/game_sa/CPed.h

Fix wrong 'm_dwUsageType' field size

Fix CPed.h

---

plugin_vc/game_vc/CTheScripts.cpp
plugin_vc/game_vc/CTheScripts.h

Adding CTheScript::IsPlayerOnAMission , returns as a bool

---

examples/UniversalTurnlights/Main.cpp

Was activating even with the vehicle broken or sunk.

Better activation conditions

---

tools/templates/codeblocks/pluginsdk/wizard.xrc

https://github.com/DK22Pac/plugin-sdk/issues/104

Fix codeblocks template

---

examples/GPS/Main.cpp

"m_vPosition" is called "m_vectPos" in CRadar.h and "m_nBlipDisplayFlag" is named "m_nBlipDisplay"
Compiles successfully now

Update Main.cpp in GPS example for San Andreas

---

shared/extensions/Shader.cpp
shared/extensions/Shader.h

fix(Shader): GetD3DDevice() Call to GetD3DDevice<IDirect3DDevice9>()

---

plugin_sa/game_sa/CSprite.cpp
plugin_sa/game_sa/CSprite.h

Added new sprite functions for GTA SA

New sprite functions for SA

---

injector/assembly.hpp

This file used to have inline assembly that would only compile with msvc, a new code path was added for other compilers, but keeping the original assembly exactly so that compilation with msvc will continue to generate the exact same instructions.
A summary of the changes:
- When msvc isn't used to compile this file the preprocesor will emit a warning instead of an error with a message that lets the user know he's doing something that isn't supported.
- included the utility and memory headers from the standard library
- added a version for the inline assembly that can be compiled with Mingw
This is the generated machine code of the assembly for and used only for mingw as compiled by mingw:
```
Disassembly of section .text$_ZN8injector12injector_asm22make_reg_pack_and_callINS0_7wrapperI10st …
```

Fix: assembly.hpp now compiles with mingw

---

tools/myplugin-gen/premake/gtasa.lua

The executable is called "gta_sa.exe". I can't confirm if this is the case on all versions of the game, but I don't remember the seeing a different name for the executable.

Fix typo for debug command

---

README.md

correcting some words in README.md file , like **_compuer_** to **computer**

correcting some english words

---

shared/Other.h

Fixed newly introduced warnings in Other.h

Fix warnings.

---

tools/premake/premake5.lua

Fixed inconsistent usage of tabs/spaces for indentations.
Enabled multi-processor compilation. In my case reduces compile time to 25%.

Premake updates

---

plugin_sa/game_sa/RenderWare.cpp
tools/premake/premake5.lua

Fix example projects not building due to lack of RW includes.

Fix missing RW

---

tools/premake/premake5.lua

For example plugin projects configured:
* post build event copying generated ASI into game's directory
* debugger

Configure debugging for example projects

---

plugin_sa/game_sa/CRoadBlocks.cpp

Fixes https://github.com/DK22Pac/plugin-sdk/issues/189

Fix address of CRoadBlocks::aScriptRoadBlocks

---

injector/hooking.hpp
injector/injector.hpp
plugin_III/game_III/CVector.h
shared/extensions/ScriptCommands.h

Fix bug in injector::MakeRelativeOffset

---

plugin_sa/game_sa/CStreaming.h
plugin_sa/game_sa/CVehicleModelInfo.cpp
plugin_sa/game_sa/CVehicleModelInfo.h

Tested in game. Should be fine this time around.

!fixup `CVehicleModelnfo` & `CStreaming` compile issues 

---

plugin_III/game_III/CFont.cpp
plugin_III/game_III/CFont.h
plugin_III/game_III/CMessages.cpp
plugin_III/game_III/CMessages.h
plugin_III/game_III/CPager.cpp
plugin_III/game_III/CPager.h

* Fixed SDK compilation errors for GTA3
* Added missing const to some function arguments in CPager
* Fixed wide to ASCII conversions in CPager

Fixed const related build errors

---

plugin_III/game_III/CControllerConfigManager.cpp
plugin_III/game_III/CControllerConfigManager.h

function prototypes taken from re3, addresses from kenking's idb

Update CControllerConfigManager (GTA3)
